# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Z8_d5eMVev4GXarolplNIJkuLB3egVT
"""

from transliterate import to_cyrillic, to_latin

matn = input("Matn kiriting: ")
print(to_cyrillic(matn))

"""if matn.isascii():
    print(to_cyrillic(matn))
else:
    print(to_latin(matn))"""